### ISSUE TITLE
[TRACKING] 1.0 To Do List

### ISSUE THREAD

**Issue by aboodilatif** [BanditSim/OERK-Riyadh-KKIA#1]
## **To-Do list for 1.0:**

# Airport Design

- [x] Taxiways/Aprons
- [x] Parking Stands
- [x] Custom Taxi Line Textures
- [x] Taxi Lines
- [ ] Taxiway signs
- [ ] Ground clutter
- [ ] Hold Short Points
- [x] RWY Hold Short Points
- [x] Edge Lighting Main Airport
- [x] Edge Lighting GA/Maintenance
- [ ] Custom Ground Markings (Taxiways)
- [ ] Custom Ground Markings (Old Terminals)
- [ ] Custom Ground Markings (Terminal 5)

# 3D Models

### Terminal 1
- [x] Model
- [x] UV
- [x] Textures
- [x] Lights

### Terminal 2
- [x] Model
- [x] UV Mapping
- [x] Textures
- [x] Lights

### Terminal 3
- [x] Model
- [x] UV Mapping
- [x] Textures
- [x] Lights

### Terminal 4
- [x] Model
- [x] UV Mapping
- [x] Textures
- [x] Lights

### Terminal 5
- [x] Model
- [x] UV Mapping
- [x] Textures
- [x] Lights

### Royal Terminal
- [x] Model
- [x] UV Mapping
- [x] Textures
- [ ] Lights

### GA Terminal
- [x] Model
- [x] UV Mapping
- [ ] Textures
- [x] Lights

### Ground Control Building
- [x] Model
- [ ] UV Mapping
- [ ] Textures
- [x] Lights

### Control Tower
- [x] Model
- [ ] UV Mapping
- [ ] Textures
- [ ] Lights

### Mosque
- [x] Model
- [x] UV Mapping
- [x] Textures
- [ ] Lights
