### ISSUE TITLE
[TRACKING] Long Term Wishlist

### ISSUE THREAD

**Issue by aboodilatif** [BanditSim/OERK-Riyadh-KKIA#2]
# Long Term Wishlist

## 3D Models

- [ ] Bridge
- [ ] Metro Station & Walkway
- [ ] Cargo Area
- [ ] DHL Building
- [x] Maintenance Hangars
- [ ] Random Airport Buildings
- [x] Low Poly Saudia 772
- [x] Low Poly Saudia 320
- [ ] Gate numbers in 3d
## Interiors
- [ ] Terminal 4, 3, 2 & 1 (should have the same interior)
- [ ] Terminal 5

## Airport Zones
- [ ] Maintenance Area

## Textures
- [ ] Custom gate ground markings
